### ISSUE TITLE
Mobile: scrolling through intro panels

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#69]
Does this work smoothly? Is it clear how to navigate through the story?

**Comment by katiepark** [comment]
The intro scrolls smoothly when the contents of a panel fit within the height of the viewport. This was causing some weirdness on mobile screens (because the text was huge) so I addressed that in the CSS here: d4da6a9f5b194182fb66fc57247453b297e4d5d1

But I think there is some further work that can be done in javascript to size images more intelligently. Not sure if it's worth doing that before progressing further on #67.
