### ISSUE TITLE
Remove conditional logic from the footer

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#73]
The footer at the bottom of the episodes should always be the same.

The Veriko "season ending" footer will point to both episodes.

**Comment by jjelosua** [comment]
Addressed here 567f70c

@lindamood @katiepark Since we are adding the auxiliary nav at the bottom of each episode, should we link also from `veriko` footer to the other two episodes or just let `veriko` footer serve as a season end with credits, related content, etc. and use the auxiliary navigation to get to the rest of the episodes? If we do not want links to the rest of the episodes then we can close this one.
